import dbRaw from './airports-db.json'

export interface AirportInfo {
  icao:    string
  name:    string
  city:    string
  country: string
  lat:     number
  lon:     number
}

// ── Static DB (generated by scripts/fetch-airports.mjs) ─────────────────────
// ~5 600 large + medium + scheduled-small airports, loaded once into a Map.

const DB = new Map<string, AirportInfo>(
  (dbRaw as AirportInfo[]).map((a) => [a.icao, a]),
)

// ── Manual overrides (corrections / additions not yet in OurAirports) ───────
// Only add entries here that are genuinely wrong in the generated data.
const OVERRIDES: Record<string, AirportInfo> = {
  // Example:
  // XXXX: { icao: 'XXXX', name: 'Custom Name', city: 'City', country: 'XX', lat: 0, lon: 0 },
}

// ── Public API ────────────────────────────────────────────────────────────────

/** Synchronous lookup — checks overrides first, then the generated DB. */
export function getAirport(icao: string): AirportInfo | undefined {
  const key = icao.toUpperCase()
  return OVERRIDES[key] ?? DB.get(key)
}

/** True if the ICAO is known in the static DB (no API call needed). */
export function isKnownAirport(icao: string): boolean {
  const key = icao.toUpperCase()
  return key in OVERRIDES || DB.has(key)
}

/** Total number of airports in the static DB. */
export const AIRPORT_DB_SIZE = DB.size

// ── Internal haversine (nm) ────────────────────────────────────────────────
function _distNm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R    = 3440.065
  const toR  = (d: number) => (d * Math.PI) / 180
  const dLat = toR(lat2 - lat1), dLon = toR(lon2 - lon1)
  const a    = Math.sin(dLat / 2) ** 2 + Math.cos(toR(lat1)) * Math.cos(toR(lat2)) * Math.sin(dLon / 2) ** 2
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))
}

/**
 * Find the nearest airport in the static DB to the given position.
 * maxDistNm caps the search radius (default 40 nm — covers all major airports
 * even if the SimConnect position has some drift on the ground).
 * Returns undefined if nothing is found within the radius.
 */
export function findNearestAirport(lat: number, lon: number, maxDistNm = 40): AirportInfo | undefined {
  let best: AirportInfo | undefined
  let bestDist = maxDistNm
  for (const airport of DB.values()) {
    const d = _distNm(lat, lon, airport.lat, airport.lon)
    if (d < bestDist) { bestDist = d; best = airport }
  }
  // Also check overrides
  for (const airport of Object.values(OVERRIDES)) {
    const d = _distNm(lat, lon, airport.lat, airport.lon)
    if (d < bestDist) { bestDist = d; best = airport }
  }
  return best
}

/** Convert lat/lon to SVG x/y for equirectangular projection. */
export function toSVG(lat: number, lon: number, W: number, H: number) {
  return {
    x: ((lon + 180) / 360) * W,
    y: ((90 - lat) / 180) * H,
  }
}
